site_name: Outputudy Documentation
docs_dir: src
site_dir: site

nav:
  - Home: index.md
  - Context: context.md
  - Architecture: architecture.md
  - Workflow: workflow.md
  - Testing: testing.md
  - API (Swagger): api.md
  - API (ReDoc): api_redoc.md

theme:
  name: material

plugins:
  - swagger-ui-tag
  - redoc-tag

